- name: Restablecer contraseñas desde CSV
  hosts: all
  gather_facts: no
  become: yes
  vars:
    csv_file: users.csv

  tasks:
    - name: Leer CSV localmente
      community.general.read_csv:
        path: "{{ csv_file }}"
      register: csv_data
      delegate_to: localhost

    - name: Restablecer contraseña para cada usuario
      ansible.builtin.user:
        name: "{{ item.users }}"
        password: "{{ 'Temporal.1234567' | password_hash('sha512') }}"
        update_password: always
      loop: "{{ csv_data.list }}"
      when: item.server == inventory_hostname
      notify: force-change-pass

  handlers:
    - name: force-change-pass
      ansible.builtin.command: chage -d 0 {{ item.users }}
      loop: "{{ csv_data.list }}"
      loop_control:
        loop_var: item
      when: item.server == inventory_hostname
