---
- name: Install VirtualBox Guest Additions on Debian
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Get kernel version
      shell: uname -r
      register: kernel_version
      changed_when: false

    - name: Debug kernel version
      debug:
        var: kernel_version.stdout

    - name: Set package list
      set_fact:
        package_list:
          - build-essential
          - dkms
          - "linux-headers-{{ kernel_version.stdout }}"
          - gcc
          - make

    - name: Show packages to be installed
      debug:
        var: package_list

    - name: Install required packages for Guest Additions
      apt:
        name: "{{ package_list }}"
        state: present
      register: packages_installed

    - name: Check CD-ROM device
      stat:
        path: /dev/sr0
      register: cdrom_check
      ignore_errors: yes  # Continuar incluso si el dispositivo no existe

    - name: Create mount point (conditional)
      file:
        path: /mnt/vboxguest
        state: directory
        mode: '0755'
      when: cdrom_check is defined and cdrom_check.stat is defined and cdrom_check.stat.exists

    - name: Mount Guest Additions ISO (conditional)
      mount:
        path: /mnt/vboxguest
        src: /dev/sr0
        fstype: iso9660
        state: mounted
        opts: ro
      when: cdrom_check is defined and cdrom_check.stat is defined and cdrom_check.stat.exists

    - name: Install from mounted ISO (conditional)
      command: /mnt/vboxguest/VBoxLinuxAdditions.run
      args:
        creates: /usr/sbin/VBoxService
      register: vbox_installed
      when: cdrom_check is defined and cdrom_check.stat is defined and cdrom_check.stat.exists

    - name: Alternative install from repository
      apt:
        name: virtualbox-guest-dkms
        state: present
      register: repo_install
      when: cdrom_check is not defined or cdrom_check.stat is not defined or not cdrom_check.stat.exists

    - name: Unmount ISO after installation (conditional)
      mount:
        path: /mnt/vboxguest
        state: absent
      when: cdrom_check is defined and cdrom_check.stat is defined and cdrom_check.stat.exists

    - name: Reboot if needed
      reboot:
        msg: "Rebooting after Guest Additions installation"
      when: >
        (packages_installed.changed) or
        (vbox_installed is defined and vbox_installed.changed) or
        (repo_install is defined and repo_install.changed)    