---
- name: Install NFS common utilities
  hosts: all
  become: yes
  tasks:
    - name: Ensure nfs-common is installed
      apt:
        name: nfs-common
        state: present
      when: ansible_os_family == "Debian"